### PR TITLE
Allow uploading file-like objects, allowing uploading of BytesIO/etc.

### PR DESCRIPTION
**Pull request by khazhyk**

### CODE REVIEW

**Comment by jacobgreenleaf** [comment]
Looks good, I'll test this a bit later today. Thanks!

**Comment by khazhyk** [comment]
Status?

**Comment by khazhyk** [comment]
Updated to close fd when using upload_from_path

**Comment by jacobgreenleaf** [comment]
This will be in 1.1.8.

**Comment by salty-horse** [comment]
Missing `return` at the end of `upload_from_path`. See #58.

**Pull request merged**
